package tiposdeenlacemenu;
import java.util.*;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Elemento1 = new javax.swing.JComboBox<>();
        Elemento2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Res = new javax.swing.JTextField();
        Cantidad = new javax.swing.JTextField();
        Cantidad2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Elemento1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Hidrógeno H", "2 Litio\tLi", "3 Sodio Na", "4 Potasio K", "5 Rubidio Rb", "6 Cesio Cs", "7 Francio Fr", "8 Berilio Be", "9 Magnesio Mg", "10 Calcio Ca", "11 Estroncio Sr ", "12 Bario Ba", "13 Radio Ra", "14 Escandio Sc", "15 Itrio Y", "16  Zirconio Zr", "17  Hafnio Hf", "18  Plata Ag", "19 Zinc Zn", "20 Cadmio Cd", "21 Aluminio Al", "22 Galio Ga", "23 Indio In", "24 Fluor F ", "25 Oxigeno O", "26 Germanio Ge", "27 Estaño Sn", "28 Talio Tl ", "29 Mercurio Hg", "30 Cobre Cu", "31 Oro Au", "32 Platino PT", "33 Paladio Pd", "34 Niquel Ni", "35 Cobalto Co", "36 Hierro Fe", "37 Tantalio Ta", "38 Niobio Nb", "39 Titanio Ti", "40 Rodio Rh", "41 Boro B", "42 Plomo Pb", "43 Silicio Si", "44 Fosforo P", "45 Arsenico As", "46 Bismuto Bi ", "47 Antimomio Sb", "48 Azufre S", "49 Selenio Se", "50 Telurio Te" }));
        Elemento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Elemento1ActionPerformed(evt);
            }
        });

        Elemento2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Hidrógeno H", "2 Litio\tLi", "3 Sodio Na", "4 Potasio K", "5 Rubidio Rb", "6 Cesio Cs", "7 Francio Fr", "8 Berilio Be", "9 Magnesio Mg", "10 Calcio Ca", "11 Estroncio Sr ", "12 Bario Ba", "13 Radio Ra", "14 Escandio Sc", "15 Itrio Y", "16  Zirconio Zr", "17  Hafnio Hf", "18  Plata Ag", "19 Zinc Zn", "20 Cadmio Cd", "21 Aluminio Al", "22 Galio Ga", "23 Indio In", "24 Fluor F ", "25 Oxigeno O", "26 Germanio Ge", "27 Estaño Sn", "28 Talio Tl ", "29 Mercurio Hg", "30 Cobre Cu", "31 Oro Au", "32 Platino PT", "33 Paladio Pd", "34 Niquel Ni", "35 Cobalto Co", "36 Hierro Fe", "37 Tantalio Ta", "38 Niobio Nb", "39 Titanio Ti", "40 Rodio Rh", "41 Boro B", "42 Plomo Pb", "43 Silicio Si", "44 Fosforo P", "45 Arsenico As", "46 Bismuto Bi ", "47 Antimomio Sb", "48 Azufre S", "49 Selenio Se", "50 Telurio Te", " " }));
        Elemento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Elemento2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese su Elemento");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese su Elemento");

        jButton1.setText("Comprobar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 153));
        jLabel3.setText("Oxidacion de un Compuesto");
        jLabel3.setToolTipText("");

        Res.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel4.setText("Subindice");

        jLabel5.setText("Subindice");

        jLabel6.setText("Numero de Oxidacion\n");

        jLabel7.setText("Instrucciones");

        jLabel8.setText("1.-Seleccione su Elemento");

        jLabel9.setText("2.-Indique Su Subindice");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Elemento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(Elemento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Cantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(Res, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Elemento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Elemento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Cantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Res, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(44, 44, 44))
        );

        Elemento1.getAccessibleContext().setAccessibleName("Switch1");
        Elemento2.getAccessibleContext().setAccessibleName("Switch2");
        jLabel1.getAccessibleContext().setAccessibleName("Label1.");
        jButton1.getAccessibleContext().setAccessibleName("boton1");
        jLabel3.getAccessibleContext().setAccessibleName("Titulo");
        Res.getAccessibleContext().setAccessibleName("Texto");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Elemento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Elemento1ActionPerformed
    
        
    }//GEN-LAST:event_Elemento1ActionPerformed

    private void Elemento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Elemento2ActionPerformed
    
    }//GEN-LAST:event_Elemento2ActionPerformed
   
   
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String sc[]=new String[50];
    double Oxi1[]=new double[50];
    double Oxi2[]=new double[50];
    double Oxi3[]=new double[50];
    double Oxi4[]=new double[50];
     sc[0]="H";
Oxi1[0]=1;
Oxi2[0]=-1;

sc[1]="Li";
Oxi1[1]=1;

sc[2]="Na";
Oxi1[2]=1;

sc[3]="K";
Oxi1[3]=1;

sc[4]="Rb";
Oxi1[4]=1;

sc[5]="Cs";
Oxi1[5]=1;

sc[6]="Fr";
Oxi1[6]=1;

sc[7]="Be";
Oxi1[7]=2;

sc[8]="Mg";
Oxi1[8]=2;

sc[9]="Ca";
Oxi1[9]=2;

sc[10]="Sr";
Oxi1[10]=2;

sc[11]="Ba";
Oxi1[11]=2;

sc[12]="Ra";
Oxi1[12]=2;

sc[13]="Sc";
Oxi1[13]=2;

sc[14]="Y";
Oxi1[14]=3;

sc[15]="ZR";
Oxi1[15]=4;

sc[16]="HF";
Oxi1[16]=4;

sc[17]="AG";
Oxi1[17]=1;

sc[18]="ZN";
Oxi1[18]=2;

sc[19]="CD";
Oxi1[19]=2;

sc[20]="AL";
Oxi1[20]=3;

sc[21]="GA";
Oxi1[21]=3;

sc[22]="IN";
Oxi1[22]=3;

sc[23]="F";
Oxi1[23]=-1;

sc[24]="O";
Oxi1[24]=2;
Oxi2[24]=-2;

sc[25]="GE";
Oxi1[25]=2;
Oxi2[25]=4;

sc[26]="SN";
Oxi1[26]=2;
Oxi2[26]=4;

sc[27]="TL";
Oxi1[27]=1;
Oxi2[27]=3;

sc[28]="HG";
Oxi1[28]=2;
Oxi2[28]=4;

sc[29]="CU";
Oxi1[29]=1;
Oxi2[29]=2;

sc[30]="AU";
Oxi1[30]=1;
Oxi2[30]=3;

sc[31]="PT";
Oxi1[31]=2;
Oxi2[31]=4;

sc[32]="PD";
Oxi1[32]=2;
Oxi2[32]=4;

sc[33]="NI";
Oxi1[33]=2;
Oxi2[33]=3;

sc[34]="CO";
Oxi1[34]=2;
Oxi2[34]=3;

sc[35]="FE";
Oxi1[35]=2;
Oxi2[35]=3;

sc[36]="TA";
Oxi1[36]=4;
Oxi2[36]=5;

sc[37]="NB";
Oxi1[37]=3;
Oxi2[37]=5;

sc[38]="TI";
Oxi1[38]=2;
Oxi2[38]=3;
Oxi3[38]=4;

sc[39]="RH";
Oxi1[39]=2;
Oxi2[39]=3;
Oxi3[39]=4;

sc[40]="B";
Oxi1[40]=1;
Oxi2[40]=2;
Oxi3[40]=3;

sc[41]="PB";
Oxi1[41]=2;
Oxi2[41]=4;
Oxi3[41]=-4;

sc[42]="SI";
Oxi1[42]=2;
Oxi2[42]=4;
Oxi3[42]=-4;

sc[43]="P";
Oxi1[43]=3;
Oxi2[43]=-3;
Oxi3[43]=5;

sc[44]="AS";
Oxi1[44]=3;
Oxi2[44]=-3;
Oxi3[44]=5;

sc[45]="BI";
Oxi1[45]=3;
Oxi2[45]=-3;
Oxi3[45]=5;

sc[46]="SB";
Oxi1[46]=3;
Oxi2[46]=-3;
Oxi3[46]=5;

sc[47]="S";
Oxi1[47]=-2;
Oxi2[47]=4;
Oxi3[47]=+6;

sc[48]="SE";
Oxi1[48]=-2;
Oxi2[48]=4;
Oxi3[48]=+6;

sc[49]="TE";
Oxi1[49]=-2;
Oxi2[49]=+4;
Oxi3[49]=6;

    
    int i=Elemento1.getSelectedIndex();
    int h=Elemento2.getSelectedIndex();  
    int resultado1[]=int[10],
            resultado2[]=int[10],
            resultado3[]=int[10];
    int subi[]=new int[2],
            subi2[]=int[2];
    int sub1,sub2;
    subi[0]=Oxi1[i]*sub1;
    subi[1]=Oxi2[i]*sub1;
    subi[2]=Oxi3[i]*sub1;
    subi2[0]=Oxi1[h]*sub2;
    subi2[1]=Oxi2[h]*sub2;
    subi2[2]=Oxi3[h]*sub2;
    resultado1[0]=subi[0]-subi2[0];
    resultado1[1]=subi[0]-subi2[1];
    resultado1[2]=subi[0]-subi2[2];
    resultado2[0]=subi[1]-subi2[0];
    resultado2[1]=subi[1]-subi2[1];
    resultado2[2]=subi[1]-subi2[2];
    resultado3[0]=subi[2]-subi2[0];
    resultado3[1]=subi[2]-subi2[1];
    resultado3[2]=subi[2]-subi2[2];
    
    if(resultado1[0]==0){
    System.out.println("El"+sc[i]+"Su Numero de Oxidacion es"+subi[0]+"\n"
    +"El"+sc[h]+"Su Numero de Oxidacion es"+subi2[0]+"\n");
    }
    else if(resultado1[1]==0){
    System.out.println("El"+sc[i]+"Su Numero de Oxidacion es"+subi[0]+"\n"
    +"El"+sc[h]+"Su Numero de Oxidacion es"+subi2[1]+"\n");
    }
    else if(resultado1[2]==0){
    System.out.println("El"+sc[i]+"Su Numero de Oxidacion es"+subi[0]+"\n"
    +"El"+sc[h]+"Su Numero de Oxidacion es"+subi2[2]+"\n");
    }
    else if(resultado2[0]==0){
    System.out.println("El"+sc[i]+"Su Numero de Oxidacion es"+subi[1]+"\n"
    +"El"+sc[h]+"Su Numero de Oxidacion es"+subi2[0]+"\n");
    }
    else if(resultado2[1]==0){
    System.out.println("El"+sc[i]+"Su Numero de Oxidacion es"+subi[1]+"\n"
    +"El"+sc[h]+"Su Numero de Oxidacion es"+subi2[1]+"\n");
    }
    else if(resultado2[2]==0){
    System.out.println("El"+sc[i]+"Su Numero de Oxidacion es"+subi[1]+"\n"
    +"El"+sc[h]+"Su Numero de Oxidacion es"+subi2[2]+"\n");
    }
    else if(resultado3[0]==0){
    System.out.println("El"+sc[i]+"Su Numero de Oxidacion es"+subi[2]+"\n"
    +"El"+sc[h]+"Su Numero de Oxidacion es"+subi2[0]+"\n");
    }
    else if(resultado3[1]==0){
    System.out.println("El"+sc[i]+"Su Numero de Oxidacion es"+subi[2]+"\n"
    +"El"+sc[h]+"Su Numero de Oxidacion es"+subi2[1]+"\n");
    }
    else if(resultado3[2]==0){
    System.out.println("El"+sc[i]+"Su Numero de Oxidacion es"+subi[2]+"\n"
    +"El"+sc[h]+"Su Numero de Oxidacion es"+subi2[2]+"\n");
    }
    
    
  
    
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cantidad;
    private javax.swing.JTextField Cantidad2;
    private javax.swing.JComboBox<String> Elemento1;
    private javax.swing.JComboBox<String> Elemento2;
    private javax.swing.JTextField Res;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
